#!/bin/bash

/bin/bash -lc '
set -eo pipefail
cd /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& source /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/miniconda3/etc/profile.d/conda.sh \
&& conda activate zehao_openpi \
&& export OPENPI_ROOT=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& export PATH="/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/uv-bin:$PATH" \
&& export HF_LEROBOT_HOME=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/dataset/lerobot \
&& export WANDB_MODE=offline \
&& ConfigName=pi05_keypoint_pika_pull_stick_1_debug_v21 \
&& LogName=pi05_keypoint_pika_pull_stick_1_debug_v21 \
&& uv run --project examples/realman_pika --no-sync python \
examples/realman_pika/pull_stick/visualprompt_convert_all_pika_data_to_lerobot.py \
--repo-id Zehao123/pi05_keypoint_pika_pull_stick_1_debug_v21 \
--max-episodes=1 \
&& uv run scripts/compute_norm_stats.py --config-name=${ConfigName} \
&& mkdir -p Logs/train \
&& XLA_PYTHON_CLIENT_MEM_FRACTION=0.9 uv run scripts/train.py ${ConfigName} \
--exp-name=${LogName} \
--fsdp-devices=1 \
--num-workers=0 \
--overwrite \
2>&1 | tee Logs/train/${LogName}.log
'
