#!/bin/bash

/bin/bash -lc '
set -eo pipefail
cd /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& source /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/miniconda3/etc/profile.d/conda.sh \
&& conda activate zehao_openpi \
&& export OPENPI_ROOT=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& export PATH="/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/uv-bin:$PATH" \
&& export HF_LEROBOT_HOME=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/dataset/lerobot \
&& export WANDB_MODE=offline \
&& export JAX_PLATFORMS=cpu \
&& ConfigName=pi05_recolor_pika_umi_collect_blocks_1_debug_v21 \
&& LogName=pi05_recolor_pika_umi_collect_blocks_1_debug_v21 \
&& uv run --project examples/realman_pika --no-sync python \
examples/realman_pika/collect_block/visualprompt_convert_pika_data_to_lerobot.py \
--data-dir /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/dataset/pika/collect_blocks_0824 \
--repo-id Zehao123/pi05_recolor_pika_umi_collect_blocks_1_debug_v21 \
--max-episodes 1 \
--sam3.target-rgb 255 255 0 \
--preview-video /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/tmp_dir/pi05_recolor_collect_blocks_1_debug_yellow.mp4 \
--overwrite \
&& uv run --project . scripts/compute_norm_stats.py --config-name=${ConfigName} \
&& mkdir -p Logs/train \
&& uv run --project . scripts/train.py ${ConfigName} \
--exp-name=${LogName} \
--fsdp-devices=1 \
--num-workers=0 \
--overwrite \
2>&1 | tee Logs/train/${LogName}.log
'
