#!/bin/bash

/bin/bash -lc '
cd /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& source /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/miniconda3/etc/profile.d/conda.sh \
&& conda activate zehao_openpi \
&& export OPENPI_ROOT=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& export PATH="/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/uv-bin:$PATH" \
&& export HF_LEROBOT_HOME=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/dataset/lerobot \
&& export WANDB_MODE=offline \
&& environment=realmanpika_umi \
&& LogName=realmanpika_umi_CollectBlocks_8workers \
&& XLA_PYTHON_CLIENT_MEM_FRACTION=0.9 uv run scripts/train.py pi05_${environment} \
--exp-name=${LogName} \
--fsdp-devices=4 \
--num-workers=8 \
--overwrite \
2>&1 | tee Logs/train/${LogName}.log
'