#!/bin/bash

/bin/bash -lc '
cd /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& source /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/miniconda3/etc/profile.d/conda.sh \
&& conda activate zehao_openpi \
&& export OPENPI_ROOT=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/openpi \
&& export PATH="/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/uv-bin:$PATH" \
&& export HF_LEROBOT_HOME=/inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/dataset/lerobot \
&& uv run --project examples/realman_pika \
python examples/realman_pika/visualprompt_convert_pika_data_to_lerobot.py \
--data-dir /inspire/hdd/project/robot-dna/baojiachun-CZXS25130063/zehao/dataset/pika/collect_blocks_0824
'
